-- MT Proof Engine: complete bootstrap for a fresh Supabase project.
-- Generated by scripts/build-bootstrap.sh from supabase/migrations/*.sql
-- and supabase/seed.sql. Do not edit directly.
-- Paste into the Supabase dashboard SQL editor and run once against a
-- clean database; it is not idempotent.

-- ============================================================
-- 0001_schema.sql
-- ============================================================
-- MT Proof Engine: core schema
-- Claims and Proof Points are first-class entities, not text inside documents.

create extension if not exists "pgcrypto";

-- Helper functions that RLS policies call live here rather than in `public`,
-- so PostgREST does not expose them as callable REST endpoints.
create schema if not exists private;
grant usage on schema private to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type user_role as enum ('contributor', 'marketing', 'sales', 'leadership');
create type story_type as enum ('project_delivery', 'equipment_upgrade', 'testwork_study', 'plant_optimisation', 'service_partnership');
create type story_status as enum ('draft', 'submitted', 'processing', 'brief_ready', 'in_review', 'reviewed');
create type input_kind as enum ('voice', 'file', 'text');
create type claim_status as enum ('candidate', 'developing', 'proven', 'retired');
create type confidence_level as enum ('confirmed', 'reported', 'missing');
create type approval_status as enum ('public', 'needs_approval', 'internal_only');
create type review_status as enum ('pending', 'confirmed', 'rejected');
create type case_study_status as enum ('draft', 'in_review', 'client_approval', 'published');
create type spin_type as enum ('situation', 'problem', 'implication', 'need_payoff');
create type gap_status as enum ('open', 'chasing', 'resolved');
create type suggestion_status as enum ('suggested', 'approved', 'dismissed');

-- ---------------------------------------------------------------------------
-- Users (mirrors auth.users; role is assigned by the Marketing Owner)
-- ---------------------------------------------------------------------------
create table users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  name text,
  role user_role not null default 'contributor',
  created_at timestamptz not null default now()
);

-- Mirrors a new auth user into public.users. Trigger-only: EXECUTE is revoked
-- below so it is not reachable as an RPC. Triggers check EXECUTE at creation
-- time, not at fire time, so the trigger keeps working.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Role of the calling user; used throughout the RLS policies below.
create or replace function private.current_user_role()
returns user_role
language sql
security definer set search_path = public
stable
as $$
  select role from public.users where id = auth.uid();
$$;

revoke execute on function private.current_user_role() from public;
grant execute on function private.current_user_role() to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Reference data (seeded, editable by the Marketing Owner)
-- ---------------------------------------------------------------------------
create table personas (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table product_tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  color text, -- secondary palette key, e.g. 'ocean'
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Stories: a raw captured win. One client, one narrative arc.
-- ---------------------------------------------------------------------------
create table stories (
  id uuid primary key default gen_random_uuid(),
  contributor_id uuid references users (id) on delete set null,
  client_name text,
  commodity text,
  location text,
  story_type story_type,
  status story_status not null default 'draft',
  scope_elements text[] not null default '{}',
  date_start text, -- fuzzy dates ("early 2023") come from voice; keep as text
  date_end text,
  current_status text,
  product_tags text[] not null default '{}',
  -- pipeline progress, shown to the Marketing Owner
  pipeline_stage text,
  pipeline_error text,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Everything the contributor gave us: voice notes, files, typed text.
create table story_inputs (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references stories (id) on delete cascade,
  kind input_kind not null,
  storage_path text,
  file_name text,
  mime_type text,
  transcript_or_text text,
  transcription_status text, -- pending | done | failed | skipped (voice/audio only)
  question_number int, -- which capture question this answers, null for file drops
  created_at timestamptz not null default now()
);

-- Stage 1 output: the structured intake brief.
create table briefs (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references stories (id) on delete cascade,
  snapshot_json jsonb,
  challenge_draft text,
  approach_draft text,
  pullquote_suggestion text,
  raw_json jsonb,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Claims: statements of value MT wants to make in the market.
-- ---------------------------------------------------------------------------
create table claims (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  status claim_status not null default 'candidate',
  -- stress-test notes
  so_what text,
  we_do_that_too text,
  prove_it text,
  personas text[] not null default '{}',
  product_tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Proof points: single verifiable pieces of evidence extracted from stories.
create table proof_points (
  id uuid primary key default gen_random_uuid(),
  story_id uuid references stories (id) on delete cascade,
  metric text not null,
  value text, -- '[XX]' when missing
  unit text,
  source_input_id uuid references story_inputs (id) on delete set null,
  source_note text, -- human-readable pointer into the source
  confidence confidence_level not null default 'reported',
  approval approval_status not null default 'needs_approval',
  review review_status not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

create table claim_proof_points (
  claim_id uuid not null references claims (id) on delete cascade,
  proof_point_id uuid not null references proof_points (id) on delete cascade,
  primary key (claim_id, proof_point_id)
);

-- ---------------------------------------------------------------------------
-- Case studies, quotes, gaps
-- ---------------------------------------------------------------------------
create table case_studies (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references stories (id) on delete cascade,
  status case_study_status not null default 'draft',
  title text,
  meta_strip text, -- client / commodity / location / dates line
  pullquote text,
  challenge text,
  approach text,
  featured_proof_point_ids uuid[] not null default '{}',
  featured_claim_ids uuid[] not null default '{}',
  cta_text text,
  published_url text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table client_quotes (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references stories (id) on delete cascade,
  quote_text text not null,
  speaker text,
  context text,
  approval approval_status not null default 'needs_approval',
  created_at timestamptz not null default now()
);

-- Missing numbers and unanswered questions, with a person to chase.
create table gaps (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references stories (id) on delete cascade,
  description text not null,
  owner_name text, -- "don't know, ask [name]"
  status gap_status not null default 'open',
  resolved_note text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Sales enablement and downstream content
-- ---------------------------------------------------------------------------
create table spin_questions (
  id uuid primary key default gen_random_uuid(),
  type spin_type not null,
  text text not null,
  claim_id uuid references claims (id) on delete cascade,
  story_id uuid references stories (id) on delete set null,
  story_type story_type,
  personas text[] not null default '{}',
  product_tags text[] not null default '{}',
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table social_posts (
  id uuid primary key default gen_random_uuid(),
  case_study_id uuid not null references case_studies (id) on delete cascade,
  target_role text not null, -- leadership | engineer | bd_sales | site_tech
  draft_text text not null,
  sources_note text, -- which proof points / quotes were used, for approval checks
  status suggestion_status not null default 'suggested',
  created_at timestamptz not null default now()
);

create table value_props (
  id uuid primary key default gen_random_uuid(),
  text text not null,
  personas text[] not null default '{}',
  product_tags text[] not null default '{}',
  claim_ids uuid[] not null default '{}',
  status suggestion_status not null default 'suggested',
  created_at timestamptz not null default now()
);

-- Sales "capture this" requests
create table capture_requests (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid references users (id) on delete set null,
  description text not null,
  suggested_contributor text,
  status text not null default 'open', -- open | captured | dismissed
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger stories_touch before update on stories for each row execute function touch_updated_at();
create trigger claims_touch before update on claims for each row execute function touch_updated_at();
create trigger case_studies_touch before update on case_studies for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- Roles: contributor (own stories + published case studies), marketing (full),
-- sales (read library, raise capture requests), leadership (read dashboards).
-- The AI pipeline runs server-side with the service role and bypasses RLS.
-- ---------------------------------------------------------------------------
alter table users enable row level security;
alter table personas enable row level security;
alter table product_tags enable row level security;
alter table stories enable row level security;
alter table story_inputs enable row level security;
alter table briefs enable row level security;
alter table claims enable row level security;
alter table proof_points enable row level security;
alter table claim_proof_points enable row level security;
alter table case_studies enable row level security;
alter table client_quotes enable row level security;
alter table gaps enable row level security;
alter table spin_questions enable row level security;
alter table social_posts enable row level security;
alter table value_props enable row level security;
alter table capture_requests enable row level security;

-- users
create policy users_select_own on users for select using (id = auth.uid() or private.current_user_role() = 'marketing');
create policy users_update_marketing on users for update using (private.current_user_role() = 'marketing');

-- reference data: everyone reads, marketing writes
create policy personas_read on personas for select using (auth.uid() is not null);
create policy personas_write on personas for all using (private.current_user_role() = 'marketing');
create policy product_tags_read on product_tags for select using (auth.uid() is not null);
create policy product_tags_write on product_tags for all using (private.current_user_role() = 'marketing');

-- stories: contributors own theirs; marketing/sales/leadership see all
create policy stories_insert on stories for insert with check (contributor_id = auth.uid());
create policy stories_select on stories for select
  using (contributor_id = auth.uid() or private.current_user_role() in ('marketing', 'sales', 'leadership'));
create policy stories_update on stories for update
  using (
    (contributor_id = auth.uid() and status in ('draft', 'brief_ready'))
    or private.current_user_role() = 'marketing'
  );

create policy story_inputs_insert on story_inputs for insert
  with check (exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid()));
create policy story_inputs_select on story_inputs for select
  using (
    exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid())
    or private.current_user_role() in ('marketing', 'sales', 'leadership')
  );

-- briefs: the contributor sees their own brief (result screen); library roles see all
create policy briefs_select on briefs for select
  using (
    exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid())
    or private.current_user_role() in ('marketing', 'sales', 'leadership')
  );
create policy briefs_write on briefs for all using (private.current_user_role() = 'marketing');

-- claims library: all signed-in users can read; marketing manages
create policy claims_read on claims for select using (auth.uid() is not null);
create policy claims_write on claims for all using (private.current_user_role() = 'marketing');

create policy proof_points_select on proof_points for select
  using (
    exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid())
    or private.current_user_role() in ('marketing', 'sales', 'leadership')
  );
create policy proof_points_write on proof_points for all using (private.current_user_role() = 'marketing');

create policy cpp_read on claim_proof_points for select using (auth.uid() is not null);
create policy cpp_write on claim_proof_points for all using (private.current_user_role() = 'marketing');

-- case studies: published are visible to everyone signed in; drafts to marketing
-- and the contributor who told the story
create policy case_studies_select on case_studies for select
  using (
    status = 'published'
    or private.current_user_role() in ('marketing', 'leadership')
    or exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid())
  );
create policy case_studies_write on case_studies for all using (private.current_user_role() = 'marketing');

create policy client_quotes_select on client_quotes for select
  using (
    exists (select 1 from stories s where s.id = story_id and s.contributor_id = auth.uid())
    or private.current_user_role() in ('marketing', 'sales', 'leadership')
  );
create policy client_quotes_write on client_quotes for all using (private.current_user_role() = 'marketing');

create policy gaps_select on gaps for select
  using (private.current_user_role() in ('marketing', 'leadership'));
create policy gaps_write on gaps for all using (private.current_user_role() = 'marketing');

-- SPIN questions: sales sees approved only; marketing sees and manages all
create policy spin_select on spin_questions for select
  using (
    (approved and private.current_user_role() in ('sales', 'leadership'))
    or private.current_user_role() = 'marketing'
  );
create policy spin_write on spin_questions for all using (private.current_user_role() = 'marketing');

create policy social_select on social_posts for select
  using (private.current_user_role() in ('marketing', 'leadership'));
create policy social_write on social_posts for all using (private.current_user_role() = 'marketing');

create policy value_props_select on value_props for select
  using (private.current_user_role() in ('marketing', 'sales', 'leadership'));
create policy value_props_write on value_props for all using (private.current_user_role() = 'marketing');

create policy capture_requests_insert on capture_requests for insert
  with check (requested_by = auth.uid() and private.current_user_role() in ('sales', 'marketing', 'leadership'));
create policy capture_requests_select on capture_requests for select
  using (private.current_user_role() in ('sales', 'marketing', 'leadership'));
create policy capture_requests_update on capture_requests for update
  using (private.current_user_role() = 'marketing');

-- ---------------------------------------------------------------------------
-- Indexes for the hot paths
-- ---------------------------------------------------------------------------
create index stories_status_idx on stories (status);
create index stories_contributor_idx on stories (contributor_id);
create index story_inputs_story_idx on story_inputs (story_id);
create index proof_points_story_idx on proof_points (story_id);
create index briefs_story_idx on briefs (story_id);
create index spin_claim_idx on spin_questions (claim_id);
create index gaps_story_idx on gaps (story_id);

-- ============================================================
-- 0002_storage.sql
-- ============================================================
-- Storage buckets for voice notes and dropped files.
-- All uploads and downloads go through server routes using the service role,
-- so the buckets stay private with no public policies.

insert into storage.buckets (id, name, public)
values
  ('voice-notes', 'voice-notes', false),
  ('story-files', 'story-files', false)
on conflict (id) do nothing;

-- ============================================================
-- seed.sql
-- ============================================================
-- MT Proof Engine seed data.
-- Personas and product tags, plus the Mindarie story as the first record so the
-- gaps workflow has real work from day one. [XX] values are deliberate: they are
-- missing numbers for the Marketing Owner to chase.

-- ---------------------------------------------------------------------------
-- Personas
-- ---------------------------------------------------------------------------
insert into personas (name, description) values
  ('Sceptic', 'Technical director, independent engineer. Wants evidence, distrusts marketing.'),
  ('Visionary', 'CEO, founder. Cares about the strategic story and time to first revenue.'),
  ('Project Director', 'Delivery owner. Cares about schedule, budget, single point of accountability.'),
  ('Plant Manager', 'Runs the operation. Cares about recovery, availability, downtime.'),
  ('Procurement', 'Commercial gatekeeper. Cares about total cost, risk, references.')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Product tags (secondary palette keys colour-code them in the UI)
-- ---------------------------------------------------------------------------
insert into product_tags (name, color) values
  ('Spirals', 'ocean'),
  ('Magnetic Separators', 'gold'),
  ('Electrostatic Separators', 'sun'),
  ('Testwork', 'ocean'),
  ('Process Design', 'coast'),
  ('Studies', 'coast'),
  ('Mining Method', 'red-earth'),
  ('Project Economics', 'gold'),
  ('Plant Engineering', 'coast'),
  ('Equipment Supply', 'gold'),
  ('Construction', 'red-earth'),
  ('Commissioning', 'red-earth'),
  ('Service & Support', 'coral')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- The Mindarie story
-- ---------------------------------------------------------------------------
insert into stories (id, client_name, commodity, location, story_type, status,
  scope_elements, date_start, date_end, current_status, product_tags)
values (
  '00000000-0000-0000-0000-000000000001',
  'Mindarie Mineral Sands Project',
  'Mineral sands',
  'Murray Basin, South Australia',
  'project_delivery',
  'reviewed',
  array['Testwork', 'Process Design', 'Plant Engineering', 'Equipment Supply', 'Construction', 'Commissioning'],
  '[XX]',
  '[XX]',
  'Commissioned and handed over',
  array['Testwork', 'Process Design', 'Plant Engineering', 'Equipment Supply', 'Commissioning']
);

-- The three Mindarie claims
insert into claims (id, title, description, status, so_what, we_do_that_too, prove_it, personas, product_tags) values
(
  '00000000-0000-0000-0000-000000000101',
  'The fastest path from your sample to first revenue',
  'One team takes a project from metallurgical sample to a commissioned, revenue-generating plant faster than the conventional study-tender-EPC route.',
  'developing',
  'Every quarter of delay costs a developer market confidence and raise headroom. Speed to first revenue is the metric boards and investors actually feel.',
  'Large EPCs claim speed but their model needs a completed study and a tender cycle before anything moves. Few competitors own testwork, design, manufacture and commissioning in one line of accountability.',
  'Months from engagement to commissioning versus what the client expected or others quoted, on named projects. Mindarie: 14 months reported; needs document confirmation.',
  array['Visionary', 'Project Director'],
  array['Testwork', 'Process Design', 'Commissioning']
),
(
  '00000000-0000-0000-0000-000000000102',
  'FID-grade documentation without major EPC price or timelines',
  'Study and engineering documentation an investment committee can approve first pass, delivered without the cost and calendar of a tier-one EPC.',
  'developing',
  'Developers of marginal ore bodies cannot carry major EPC study costs. Documentation that passes an investment committee unlocks the raise.',
  'Boutique consultancies produce studies too, but few can stand behind the numbers with their own testwork and equipment performance data.',
  'A named investment committee or financier accepting MT documentation first pass; study cost versus a major EPC benchmark. Values currently missing.',
  array['Visionary', 'Procurement', 'Sceptic'],
  array['Studies', 'Project Economics', 'Process Design']
),
(
  '00000000-0000-0000-0000-000000000103',
  'Whole-project development and delivery built around the asset',
  'Mining method, flowsheet, economics and plant are developed around what the ore body can support, not around a standard plant design.',
  'developing',
  'Marginal ore bodies fail conventional studies. An approach built around the asset turns "uneconomic" into a financeable project.',
  'Everyone says "tailored solutions". The difference is MT adjusting mining method and project scope against project economics in-house.',
  'A project deemed marginal under a conventional flowsheet that reached FID and production under an MT-developed approach, with the before/after economics.',
  array['Visionary', 'Sceptic', 'Project Director'],
  array['Mining Method', 'Project Economics', 'Process Design']
);

-- Company-wide candidate claims
insert into claims (title, description, status, personas, product_tags) values
(
  'Process knowledge and equipment manufacture under one roof',
  'MT designs the flowsheet and manufactures the separation equipment that delivers it, so performance accountability never splits across vendors.',
  'candidate',
  array['Sceptic', 'Procurement'],
  array['Equipment Supply', 'Process Design']
),
(
  'Proven from lab to pilot to plant',
  'Recoveries demonstrated at laboratory scale hold at pilot and at operating plant scale, documented across the same ore.',
  'candidate',
  array['Sceptic'],
  array['Testwork']
),
(
  'Measured gains at operating plants',
  'Recovery, grade and throughput improvements measured before and after MT interventions at running operations.',
  'candidate',
  array['Plant Manager', 'Sceptic'],
  array['Service & Support', 'Spirals', 'Magnetic Separators']
),
(
  'Long-term support for the life of the plant',
  'MT stays with the plant after commissioning: audits, spares, upgrades and response when it matters.',
  'candidate',
  array['Plant Manager', 'Procurement'],
  array['Service & Support']
);

-- Proof points. The 14-month figure was reported in conversation; the rest are
-- referenced without values, which is exactly the gap-chasing work the app exists for.
insert into proof_points (id, story_id, metric, value, unit, confidence, approval, review, source_note) values
(
  '00000000-0000-0000-0000-000000000201',
  '00000000-0000-0000-0000-000000000001',
  'Engagement to commissioning', '14', 'months', 'reported', 'needs_approval', 'confirmed',
  'Reported in project retrospective conversation; needs the project schedule to confirm.'
),
(
  '00000000-0000-0000-0000-000000000202',
  '00000000-0000-0000-0000-000000000001',
  'Project IRR after MT scope and flowsheet rework', '[XX]', '%', 'missing', 'needs_approval', 'pending',
  'Referenced without a value. The study comparison should hold the before/after.'
),
(
  '00000000-0000-0000-0000-000000000203',
  '00000000-0000-0000-0000-000000000001',
  'Delivered cost versus major EPC benchmark', '[XX]', '% of EPC quote', 'missing', 'needs_approval', 'pending',
  'Referenced without a value. Needs the tender comparison or board paper.'
),
(
  '00000000-0000-0000-0000-000000000204',
  '00000000-0000-0000-0000-000000000001',
  'Production tonnes versus schedule in first year', '[XX]', 't', 'missing', 'needs_approval', 'pending',
  'Referenced without a value. Needs production reporting from the client.'
);

insert into claim_proof_points (claim_id, proof_point_id) values
  ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000201'),
  ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000203'),
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000202'),
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000204');

-- Gaps to chase, one per missing value
insert into gaps (story_id, description, owner_name, status) values
  ('00000000-0000-0000-0000-000000000001', 'Confirm 14 months engagement-to-commissioning against the project schedule.', null, 'open'),
  ('00000000-0000-0000-0000-000000000001', 'IRR before and after MT scope rework. Likely in the study comparison.', null, 'open'),
  ('00000000-0000-0000-0000-000000000001', 'Delivered cost versus the major EPC benchmark quote.', null, 'open'),
  ('00000000-0000-0000-0000-000000000001', 'First-year production tonnes versus schedule. Client production reports.', null, 'open'),
  ('00000000-0000-0000-0000-000000000001', 'Client approval status: can we name the project and use the numbers publicly?', null, 'open');

-- The Mindarie case study (mirrors the existing one-pager)
insert into case_studies (id, story_id, status, title, meta_strip, pullquote, challenge, approach,
  featured_proof_point_ids, featured_claim_ids, cta_text)
values (
  '00000000-0000-0000-0000-000000000301',
  '00000000-0000-0000-0000-000000000001',
  'draft',
  'From marginal ore body to commissioned plant in 14 months',
  'Mineral sands | Murray Basin, South Australia | Project delivery',
  'The conventional answer said the economics were too thin. Building the project around the asset said otherwise.',
  'The Mindarie ore body had been assessed as marginal under a conventional flowsheet and delivery model. Study costs and EPC timelines threatened the economics before the project could reach a decision.',
  'MT developed the mining method, flowsheet and project scope around what the asset could support, carried its own testwork through design, manufactured the separation equipment, and took the plant through construction to commissioning as one accountable team.',
  array['00000000-0000-0000-0000-000000000201'::uuid, '00000000-0000-0000-0000-000000000202'::uuid, '00000000-0000-0000-0000-000000000203'::uuid, '00000000-0000-0000-0000-000000000204'::uuid],
  array['00000000-0000-0000-0000-000000000101'::uuid, '00000000-0000-0000-0000-000000000102'::uuid, '00000000-0000-0000-0000-000000000103'::uuid],
  'Talk to us about the path from your sample to first revenue.'
);
