#!/usr/bin/env bash
# Regenerate supabase/bootstrap.sql from the migrations and the seed file.
#
# bootstrap.sql is the one-paste form of the database, for the Supabase
# dashboard SQL editor. Run this after changing any migration or the seed.

set -euo pipefail

cd "$(dirname "$0")/.."
OUT=supabase/bootstrap.sql

{
  echo "-- MT Proof Engine: complete bootstrap for a fresh Supabase project."
  echo "-- Generated by scripts/build-bootstrap.sh from supabase/migrations/*.sql"
  echo "-- and supabase/seed.sql. Do not edit directly."
  echo "-- Paste into the Supabase dashboard SQL editor and run once against a"
  echo "-- clean database; it is not idempotent."
  echo

  for f in supabase/migrations/*.sql; do
    echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    cat "$f"
    echo
  done

  echo "-- ============================================================"
  echo "-- seed.sql"
  echo "-- ============================================================"
  cat supabase/seed.sql
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
